# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('dataInclusao', models.DateTimeField(verbose_name='date published')),
                ('timestampSensor', models.DateTimeField(verbose_name='date generated')),
                ('recurso', models.CharField(max_length=200)),
                ('valor', models.FloatField(default=0.0)),
                ('experimento', models.CharField(max_length=200)),
                ('idRequisicao', models.IntegerField(default=0)),
                ('idResposta', models.IntegerField(default=0)),
            ],
        ),
    ]
