# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simoni', '0002_auto_20170630_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='diffTempos',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='diff date'),
            preserve_default=False,
        ),
    ]
